server:
  port: 8990

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
      
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: epam
    password: epam
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true    
    